import { ThemeDefinition } from '../types';

export const appleMintTheme: ThemeDefinition = {
    id: 'apple-mint',
    name: 'Мята',
    isCustom: false,
    scheme: {
        "light": {
            "dashboardBackgroundType": "gradient",
            "dashboardBackgroundColor1": "#F0F7F6",
            "dashboardBackgroundColor2": "#E6F0EF",
            "cardOpacity": 0.85,
            "panelOpacity": 0.75,
            "cardBorderRadius": 16,
            "cardBorderWidth": 0,
            "cardBorderColor": "#D1FAE5",
            "cardBorderColorOn": "#059669",
            "iconBackgroundShape": "circle",
            "iconBackgroundColorOn": "rgba(255, 255, 255, 0.9)",
            "iconBackgroundColorOff": "rgba(255, 255, 255, 0.4)",
            "cardBackground": "rgba(255, 255, 255, 0.8)",
            "cardBackgroundOn": "rgba(255, 255, 255, 0.95)",
            "tabTextColor": "#374151",
            "activeTabTextColor": "#065F46",
            "tabIndicatorColor": "#059669",
            "thermostatHandleColor": "#FFFFFF",
            "thermostatDialTextColor": "#065F46",
            "thermostatDialLabelColor": "#374151",
            "thermostatHeatingColor": "#F97316",
            "thermostatCoolingColor": "#3B82F6",
            "clockTextColor": "#065F46",
            "nameTextColor": "#374151",
            "statusTextColor": "#6B7280",
            "valueTextColor": "#065F46",
            "unitTextColor": "#065F46",
            "nameTextColorOn": "#065F46",
            "statusTextColorOn": "#374151",
            "valueTextColorOn": "#065F46",
            "unitTextColorOn": "#065F46"
        },
        "dark": {
            "dashboardBackgroundType": "color",
            "dashboardBackgroundColor1": "#1A2421",
            "cardOpacity": 0.8,
            "panelOpacity": 0.75,
            "cardBorderRadius": 16,
            "cardBorderWidth": 0,
            "cardBorderColor": "#1E293B",
            "cardBorderColorOn": "#34D399",
            "iconBackgroundShape": "circle",
            "iconBackgroundColorOn": "rgba(255, 255, 255, 0.15)",
            "iconBackgroundColorOff": "rgba(255, 255, 255, 0.05)",
            "cardBackground": "rgba(30, 41, 59, 0.8)",
            "cardBackgroundOn": "rgba(38, 52, 75, 0.85)",
            "tabTextColor": "#9CA3AF",
            "activeTabTextColor": "#A7F3D0",
            "tabIndicatorColor": "#34D399",
            "thermostatHandleColor": "#1A2421",
            "thermostatDialTextColor": "#A7F3D0",
            "thermostatDialLabelColor": "#9CA3AF",
            "thermostatHeatingColor": "#F28C18",
            "thermostatCoolingColor": "#0A84FF",
            "clockTextColor": "#A7F3D0",
            "nameTextColor": "#D1D5DB",
            "statusTextColor": "#9CA3AF",
            "valueTextColor": "#A7F3D0",
            "unitTextColor": "#A7F3D0",
            "nameTextColorOn": "#A7F3D0",
            "statusTextColorOn": "#9CA3AF",
            "valueTextColorOn": "#A7F3D0",
            "unitTextColorOn": "#A7F3D0"
        }
    }
};
