import { ThemeDefinition } from '../types';

export const deepSpaceTheme: ThemeDefinition = {
    id: 'deep-space',
    name: 'Глубокий космос',
    isCustom: false,
    scheme: {
        "light": {
            "dashboardBackgroundType": "gradient",
            "dashboardBackgroundColor1": "#D4DEE7",
            "dashboardBackgroundColor2": "#BCC8D6",
            "cardOpacity": 0.85,
            "panelOpacity": 0.75,
            "cardBorderRadius": 16,
            "cardBorderWidth": 0,
            "cardBorderColor": "#E2E8F0",
            "cardBorderColorOn": "#3182CE",
            "iconBackgroundShape": "circle",
            "iconBackgroundColorOn": "rgba(255, 255, 255, 0.9)",
            "iconBackgroundColorOff": "rgba(255, 255, 255, 0.4)",
            "cardBackground": "rgba(255, 255, 255, 0.7)",
            "cardBackgroundOn": "rgba(255, 255, 255, 0.9)",
            "tabTextColor": "#4A5568",
            "activeTabTextColor": "#1A202C",
            "tabIndicatorColor": "#2D3748",
            "thermostatHandleColor": "#FFFFFF",
            "thermostatDialTextColor": "#1A202C",
            "thermostatDialLabelColor": "#4A5568",
            "thermostatHeatingColor": "#DD6B20",
            "thermostatCoolingColor": "#3182CE",
            "clockTextColor": "#1A202C",
            "nameTextColor": "#2D3748",
            "statusTextColor": "#718096",
            "valueTextColor": "#1A202C",
            "unitTextColor": "#1A202C",
            "nameTextColorOn": "#1A202C",
            "statusTextColorOn": "#2D3748",
            "valueTextColorOn": "#1A202C",
            "unitTextColorOn": "#1A202C"
        },
        "dark": {
            "dashboardBackgroundType": "color",
            "dashboardBackgroundColor1": "#0a0f14",
            "cardOpacity": 0.8,
            "panelOpacity": 0.7,
            "cardBorderRadius": 16,
            "cardBorderWidth": 0,
            "cardBorderColor": "#2D3748",
            "cardBorderColorOn": "#89B3F8",
            "iconBackgroundShape": "circle",
            "iconBackgroundColorOn": "rgba(255, 255, 255, 0.15)",
            "iconBackgroundColorOff": "rgba(255, 255, 255, 0.05)",
            "cardBackground": "rgba(18, 25, 35, 0.8)",
            "cardBackgroundOn": "rgba(25, 33, 45, 0.9)",
            "tabTextColor": "#9FB1CC",
            "activeTabTextColor": "#EAF0F6",
            "tabIndicatorColor": "#89B3F8",
            "thermostatHandleColor": "#121923",
            "thermostatDialTextColor": "#EAF0F6",
            "thermostatDialLabelColor": "#9FB1CC",
            "thermostatHeatingColor": "#F6AD55",
            "thermostatCoolingColor": "#63B3ED",
            "clockTextColor": "#EAF0F6",
            "nameTextColor": "#CBD5E0",
            "statusTextColor": "#A0AEC0",
            "valueTextColor": "#EAF0F6",
            "unitTextColor": "#EAF0F6",
            "nameTextColorOn": "#EAF0F6",
            "statusTextColorOn": "#CBD5E0",
            "valueTextColorOn": "#EAF0F6",
            "unitTextColorOn": "#EAF0F6"
        }
    }
};
