import { ThemeDefinition } from '../types';

export const futuristicTheme: ThemeDefinition = {
    id: 'futuristic',
    name: 'Футуристика',
    isCustom: false,
    scheme: {
        "light": {
            "dashboardBackgroundType": "gradient",
            "dashboardBackgroundColor1": "#f5f7fa",
            "dashboardBackgroundColor2": "#eef2f7",
            "cardOpacity": 0.8,
            "panelOpacity": 0.7,
            "cardBorderRadius": 16,
            "cardBorderWidth": 0,
            "cardBorderColor": "#D1D9E6",
            "cardBorderColorOn": "#007A7A",
            "iconBackgroundShape": "circle",
            "iconBackgroundColorOn": "rgba(255, 255, 255, 0.9)",
            "iconBackgroundColorOff": "rgba(255, 255, 255, 0.4)",
            "cardBackground": "rgba(255, 255, 255, 0.8)",
            "cardBackgroundOn": "rgba(255, 255, 255, 1.0)",
            "tabTextColor": "#5c677d",
            "activeTabTextColor": "#007a7a",
            "tabIndicatorColor": "#007a7a",
            "thermostatHandleColor": "#FFFFFF",
            "thermostatDialTextColor": "#005a5a",
            "thermostatDialLabelColor": "#5c677d",
            "thermostatHeatingColor": "#ff6b6b",
            "thermostatCoolingColor": "#4d96ff",
            "clockTextColor": "#005a5a",
            "nameTextColor": "#333d4f",
            "statusTextColor": "#5c677d",
            "valueTextColor": "#005a5a",
            "unitTextColor": "#005a5a",
            "nameTextColorOn": "#005a5a",
            "statusTextColorOn": "#5c677d",
            "valueTextColorOn": "#005a5a",
            "unitTextColorOn": "#005a5a"
        },
        "dark": {
            "dashboardBackgroundType": "gradient",
            "dashboardBackgroundColor1": "#1a2a3a",
            "dashboardBackgroundColor2": "#101a24",
            "cardOpacity": 0.8,
            "panelOpacity": 0.7,
            "cardBorderRadius": 16,
            "cardBorderWidth": 0,
            "cardBorderColor": "#2A3A4A",
            "cardBorderColorOn": "#00DADA",
            "iconBackgroundShape": "circle",
            "iconBackgroundColorOn": "rgba(255, 255, 255, 0.15)",
            "iconBackgroundColorOff": "rgba(255, 255, 255, 0.05)",
            "cardBackground": "rgba(20, 30, 40, 0.8)",
            "cardBackgroundOn": "rgba(25, 35, 45, 1.0)",
            "tabTextColor": "#9cb3cc",
            "activeTabTextColor": "#00dada",
            "tabIndicatorColor": "#00dada",
            "thermostatHandleColor": "#1a2a3a",
            "thermostatDialTextColor": "#00dada",
            "thermostatDialLabelColor": "#9cb3cc",
            "thermostatHeatingColor": "#ff8787",
            "thermostatCoolingColor": "#74afff",
            "clockTextColor": "#00dada",
            "nameTextColor": "#c0d4e7",
            "statusTextColor": "#9cb3cc",
            "valueTextColor": "#00dada",
            "unitTextColor": "#00dada",
            "nameTextColorOn": "#00dada",
            "statusTextColorOn": "#9cb3cc",
            "valueTextColorOn": "#00dada",
            "unitTextColorOn": "#00dada"
        }
    }
};
